SCHEMA schema_UT_family_1;

TYPE Name = STRING;
END_TYPE;

ENTITY Person
   ABSTRACT SUPERTYPE OF (ONEOF (Male, Female));
     name : Name;
     mother : OPTIONAL Female;
     father: OPTIONAL Male;
END_ENTITY;

ENTITY Female
   SUBTYPE OF (Person);
   INVERSE
     motherof : SET [0:?] OF Person FOR mother;
END_ENTITY;

ENTITY Male
   SUBTYPE OF (Person);
   INVERSE
     fatherof : SET [0:?] OF Person FOR father;
END_ENTITY;

END_SCHEMA;
